#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index_map:
    path: /map
    controller: App\Controller\MapController::index

settings_map:
    path: /settings
    controller: App\Controller\MapController::mapSettings

get_route:
    path: /get_route/{route_id}
    controller: App\Controller\MapController::getRouteJSON
    requirements:
        page: '\d+'

# tests
save_coordinate:
    path: /save
    controller: App\Controller\MapController::saveCoordinate

get_coordintes:
    path: /get_coordintes
    controller: App\Controller\MapController::getCoordinates
